### ISSUE TITLE
Add Eslint rules for Studel

### ISSUE THREAD

**Issue by xolir** [strudeljs/roadmap#1]
Prefer @El decorator in single line 
Prefer @El decorator to map to $ prefixed variable
Prefer @El on top
Prefer init() on top
Prefer Strudel DOM Method instead of DOM

**Comment by mateuszluczak** [comment]
Thanks for the ideas! I've created a milestone for the eslint plugin based on your submissions:

https://github.com/strudeljs/eslint-plugin-strudel/milestone/1

> Prefer Strudel DOM Method instead of DOM
This one might seem a little bit difficult to do correctly so I didn't include it in milestone.
